---
- name: Playbook equipo pfsense
  # A quienes se les va a operar 
  hosts: web
  gather_facts: true
  become: true
  vars:
    scheduled_reboot_time: "2024-10-25 14:00" 
    
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"

    # Actualizacion de paquetes     
    - name: Actualizar paquetes en Red Hat/CentOS/Oracle Linux
      dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      register: dnf_update  

     name: Programar reinicio en una fecha determinada
      command: "shutdown -r {{ scheduled_reboot_time }}"
      when: dnf_update.changed
      register: shutdown_result  # Registrar resultado del comando

    - name: Verificar si la programaci贸n de reinicio fue exitosa
      debug:
        msg: "Programaci贸n de reinicio ejecutada correctamente"
      when: shutdown_result.rc == 0

    - name: Mostrar error si la programaci贸n de reinicio fall贸
      debug:
        msg: "Error al programar el reinicio"
      when: shutdown_result.rc != 0 
