---
- name: Actualizar paquetes y programar reinicio en una fecha determinada
  hosts: web
  become: true
  gather_facts: true
  vars:
    scheduled_reboot_time: "2024-10-25 14:00"  # Variable para la fecha y hora del reinicio
  tasks:
    - name: Actualizar paquetes en Red Hat/CentOS/Oracle Linux
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      register: dnf_update

    - name: Programar reinicio en una fecha determinada
      command: "shutdown -r {{ scheduled_reboot_time }}"
      when: dnf_update.changed
      register: shutdown_result  # Registrar resultado del comando

    - name: Notificar en Slack si la programaci贸n de reinicio fue exitosa
      community.general.slack:
        token: "xoxb-your-slack-token-here"
        msg: "Programaci贸n de reinicio ejecutada correctamente para {{ inventory_hostname }} a las {{ scheduled_reboot_time }}."
        channel: "#notificaciones"
      when: shutdown_result.rc == 0

    - name: Notificar en Slack si la programaci贸n de reinicio fall贸
      community.general.slack:
        token: "xoxb-your-slack-token-here"
        msg: "Error al programar el reinicio en {{ inventory_hostname }}."
        channel: "#notificaciones"
      when: shutdown_result.rc != 0


