---
- name: Playbook equipo pfsense
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"

    # Actualizacion de paquetes     
    - name: Actualizar paquetes en Red Hat/CentOS/Oracle Linux
      dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      register: dnf_update  

    - name: Programar reinicio en una fecha determinada
      command: shutdown -r 2024-10-25 14:00
      when: dnf_update.changed  
      ignore_errors: true  
