---
# playbook equipo pfsense  
- name: Actualizar paquetes y programar reinicio en una fecha determinada
  hosts: web
  become: true
  gather_facts: true
  
  tasks:
    - name: Actualizar paquetes en Red Hat/CentOS/Oracle Linux
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      register: dnf_update

    - name: Programar reinicio en una fecha determinada
      ansible.builtin.reboot:
      when: dnf_update.changed
      register: reboot_result  # Registrar el resultado del reinicio





